Relax required Python 3.6 version
This allows Python 3.6.1 or greater to be installed, which fixes an
import error from the `typing` module:

    ImportError: cannot import name 'AsyncGenerator'

which in turn fixes the failing docs build in pymt.

h/t https://github.com/pgjones/quart/issues/19#issuecomment-385890334